[package]
name = "freq"
version = "0.1.0"
authors = ["Ryan Castellucci <code@ryanc.org>"]
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
counter = { version = "0.5" }
