[package]
name = "freq"
version = "0.2.1"
authors = ["Ryan Castellucci <code@ryanc.org>"]
edition = "2021"
resolver = "2"

[dependencies]
clap = { version = "4", features = ["derive"] }
counter = { version = "0.5" }
build-info = "0"
semver = "1"

[build-dependencies]
build-info = "0"
build-info-build = "0"

[features]
default = ["egg"]
egg = []

[[bin]]
name = "freq"
test = false
bench = false

[profile.lto]
inherits = "release"
lto = true
